jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud